#pragma once

/// @file Mountain.hpp
/// @brief A convenient way of including every header of this framework.
/// @note You rarely need to use this. This is mainly for precompiled headers.

#include "Mountain/PrecompiledHeader.hpp"

#include "Mountain/Audio/Audio.hpp"
#include "Mountain/Audio/AudioBuffer.hpp"
#include "Mountain/Audio/AudioContext.hpp"
#include "Mountain/Audio/AudioDevice.hpp"

#include "Mountain/Collision/Circle.hpp"
#include "Mountain/Collision/Collider.hpp"
#include "Mountain/Collision/ColliderList.hpp"
#include "Mountain/Collision/Collision.hpp"
#include "Mountain/Collision/Grid.hpp"
#include "Mountain/Collision/Hitbox.hpp"

#include "Mountain/Containers/Array.hpp"
#include "Mountain/Containers/ContiguousIterator.hpp"
#include "Mountain/Containers/EnumerableExt.hpp"
#include "Mountain/Containers/FunctionTypes.hpp"
#include "Mountain/Containers/List.hpp"

#include "Mountain/Ecs/Component/AudioListener.hpp"
#include "Mountain/Ecs/Component/AudioListener.hpp"
#include "Mountain/Ecs/Component/AudioSource.hpp"
#include "Mountain/Ecs/Component/Component.hpp"
#include "Mountain/Ecs/Component/Sprite.hpp"
#include "Mountain/Ecs/Component/StateMachine.hpp"

#include "Mountain/Ecs/Entity.hpp"
#include "Mountain/Ecs/EntityList.hpp"
#include "Mountain/Ecs/Scene.hpp"

#include "Mountain/Exceptions/ArgumentException.hpp"
#include "Mountain/Exceptions/Exception.hpp"
#include "Mountain/Exceptions/ThrowHelper.hpp"

#include "Mountain/FileSystem/Directory.hpp"
#include "Mountain/FileSystem/Entry.hpp"
#include "Mountain/FileSystem/File.hpp"
#include "Mountain/FileSystem/FileManager.hpp"

#include "Mountain/Input/GamepadInput.hpp"
#include "Mountain/Input/Input.hpp"
#include "Mountain/Input/KeyboardInput.hpp"
#include "Mountain/Input/MouseInput.hpp"
#include "Mountain/Input/Time.hpp"

#include "Mountain/Rendering/Draw.hpp"
#include "Mountain/Rendering/Effect.hpp"
#include "Mountain/Rendering/GpuBuffer.hpp"
#include "Mountain/Rendering/GpuTexture.hpp"
#include "Mountain/Rendering/GpuVertexArray.hpp"
#include "Mountain/Rendering/Graphics.hpp"
#include "Mountain/Rendering/LightSource.hpp"
#include "Mountain/Rendering/ParticleSystem.hpp"
#include "Mountain/Rendering/ParticleSystemModules.hpp"
#include "Mountain/Rendering/Renderer.hpp"
#include "Mountain/Rendering/RenderTarget.hpp"

#include "Mountain/Resource/AudioTrack.hpp"
#include "Mountain/Resource/ComputeShader.hpp"
#include "Mountain/Resource/Font.hpp"
#include "Mountain/Resource/Resource.hpp"
#include "Mountain/Resource/ResourceManager.hpp"
#include "Mountain/Resource/Shader.hpp"
#include "Mountain/Resource/ShaderBase.hpp"
#include "Mountain/Resource/Texture.hpp"

#include "Mountain/Utils/Color.hpp"
#include "Mountain/Utils/Coroutine.hpp"
#include "Mountain/Utils/DateTime.hpp"
#include "Mountain/Utils/Event.hpp"
#include "Mountain/Utils/FileSystemWatcher.hpp"
#include "Mountain/Utils/Formatter.hpp"
#include "Mountain/Utils/Guid.hpp"
#include "Mountain/Utils/ImGuiUtils.hpp"
#include "Mountain/Utils/Logger.hpp"
#include "Mountain/Utils/MessageBox.hpp"
#include "Mountain/Utils/MetaProgramming.hpp"
#include "Mountain/Utils/Pointer.hpp"
#include "Mountain/Utils/Random.hpp"
#include "Mountain/Utils/Rectangle.hpp"
#include "Mountain/Utils/ReferenceCounter.hpp"
#include "Mountain/Utils/Requirements.hpp"
#include "Mountain/Utils/Stopwatch.hpp"
#include "Mountain/Utils/TimeSpan.hpp"
#include "Mountain/Utils/TsQueue.hpp"
#include "Mountain/Utils/Utils.hpp"
//#include "Mountain/Utils/Windows.hpp" We do not include Windows to avoid any naming conflicts

#include "Mountain/Attributes.hpp"
#include "Mountain/CompilerSpecific.hpp"
#include "Mountain/Configuration.hpp"
#include "Mountain/Core.hpp"
#include "Mountain/Game.hpp"
#include "Mountain/Globals.hpp"
#include "Mountain/Screen.hpp"
#include "Mountain/Window.hpp"
