#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (rgba32f, binding = 0) uniform image2D outputImage;

void main()
{
    ivec2 texelCoordinates = ivec2(gl_GlobalInvocationID.xy);

    vec4 color = vec4(0.f, 0.f, 1.f, 1.f);
    color.x = float(texelCoordinates.x) / gl_NumWorkGroups.x;
    color.y = float(texelCoordinates.y) / gl_NumWorkGroups.y;

    imageStore(outputImage, texelCoordinates, color);
}
