#include "Mountain/Platform/Linux/Linux.hpp"

#include <fcntl.h>

#ifdef ENVIRONMENT_LINUX

using namespace Mountain;

/// @brief Generate cryptographically strong random bytes.
/// @details Source: https://github.com/dotnet/runtime/blob/0cf1906b274d5ab7d3ea1e11aa43af98ecb87d48/src/native/minipal/random.c#L79
/// @return 0 on success, -1 on failure.
s32 GetCryptographicallySecureRandomBytes(u8* buffer, const s32 bufferLength)
{
    ENSURE_NOT_NULL(buffer);

    // getentropy() is available on platforms like WASI (via wasi-libc, backed by
    // __wasi_random_get()) and other libc implementations. Used as a fallback when
    // getrandom() is not available or fails.
    {
        s32 offset = 0;
        while (offset < bufferLength)
        {
            // getentropy() is limited to 256 bytes per call
            usize chunk = static_cast<usize>(bufferLength - offset);
            if (chunk > 256)
                chunk = 256;
            if (getentropy(buffer + offset, chunk) < 0)
                break; // fallback to /dev/urandom

            offset += static_cast<s32>(chunk);
        }

        if (offset == bufferLength)
        {
            return 0;
        }
    }

    // Fallback to /dev/urandom
    static volatile int randDes = -1;
    static bool sMissingDevURandom;

    if (!sMissingDevURandom)
    {
        if (randDes == -1)
        {
            int fd;

            do
                fd = open("/dev/urandom", O_RDONLY | O_CLOEXEC);
            while (fd == -1 && errno == EINTR);

            if (fd != -1)
            {
                int expected = -1;
                if (!__atomic_compare_exchange_n(&randDes, &expected, fd, false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST))
                {
                    // Another thread has already set the rand_des
                    close(fd);
                }
            }
            else if (errno == ENOENT)
            {
                sMissingDevURandom = true;
            }
        }

        if (randDes != -1)
        {
            s32 offset = 0;
            do
            {
                const ssize_t n = read(randDes, buffer + offset, static_cast<usize>(bufferLength - offset));
                if (n == -1)
                {
                    if (errno == EINTR)
                        continue;

                    return -1;
                }

                offset += n;
            }

            while (offset != bufferLength);

            return 0;
        }
    }

    return -1;
}

/// @brief Generate random bytes. The generated bytes are not cryptographically strong.
/// @details Source: https://github.com/dotnet/runtime/blob/0cf1906b274d5ab7d3ea1e11aa43af98ecb87d48/src/native/minipal/random.c#L35
void GetNonCryptographicallySecureRandomBytes(u8* buffer, const s32 bufferLength)
{
    ENSURE_NOT_NULL(buffer);

    arc4random_buf(buffer, static_cast<usize>(bufferLength));
}

/// @brief @c GetSystemTimeAsTicks() return the system time as ticks (100 nanoseconds) since 00:00 01 January 1970 UTC (Unix epoch)
/// @details Source: https://github.com/dotnet/runtime/blob/286dc1501f7bc16b2b170ec68d70bb755476d4ea/src/native/libs/System.Native/pal_datetime.c#L28
s64 GetSystemTimeAsTicks()
{
    static constexpr int64_t TicksPerSecond = 10000000; /* 10^7 */
    static constexpr int64_t NanosecondsPerTick = 100;

    timespec time;
    if (clock_gettime(CLOCK_REALTIME, &time) == 0)
        return time.tv_sec * TicksPerSecond + time.tv_nsec / NanosecondsPerTick;

    // in failure we return 00:00 01 January 1970 UTC (Unix epoch)
    return 0;
}

bool Linux::Sleep(const TimeSpan duration)
{
    static constexpr int InterruptError = 4;
    static constexpr int NanosecondsPerSecond = 1000 * 1000 * 1000;

    const s64 nanoseconds = static_cast<s64>(duration.GetTotalNanoseconds());

    timespec timeSpec
    {
        .tv_sec = nanoseconds / NanosecondsPerSecond,
        .tv_nsec = nanoseconds % NanosecondsPerSecond,
    };
    timespec remaining;

    int result;

    while ((result = nanosleep(&timeSpec, &remaining)) == -1 && errno == InterruptError)
    {
        // The pause can be interrupted by a signal that was delivered to the thread.
        // Sleep again with remaining time if it happened.
        timeSpec = remaining;
    }

    return result == 0; // Any errors other than InterruptError should return false.
}

Guid Linux::NewGuid()
{
    Guid guid;
    GetCryptographicallySecureRandomBytes(reinterpret_cast<u8*>(&guid), sizeof(guid));
    return guid;
}

DateTime Linux::UtcNow() { return DateTime{static_cast<u64>(GetSystemTimeAsTicks() + DateTime::UnixEpochTicks) | DateTime::KindUtc}; }

usize Linux::GetMemoryUsage()
{
    std::ifstream file{"/proc/self/statm", std::ios::in | std::ios::binary};

    Array<c8, 20> buffer;
    file.read(buffer.GetData(), sizeof(buffer));

    file.close();

    usize result = 0;
    SCANF(buffer.GetData(), "%zu", &result);

    return result;
}

void Linux::Cleanup()
{
}

#endif
